INSERT INTO RECIPE (RECIPE_ID, INSTRUCTIONS, NUMBER_OF_SERVINGS, RECIPE_NAME, VEGETARIAN, CREATED_DATE, UPDATED_DATE) VALUES
(1, 'take bowl, add oil , add potatoes , fry them ', 1, 'Potato Fry', true, {ts '2022-08-14 01:18:32'},{ts '2022-08-14 01:18:32'});

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(1, 'POTATOES');

INSERT INTO RECIPE (RECIPE_ID, INSTRUCTIONS, NUMBER_OF_SERVINGS, RECIPE_NAME, VEGETARIAN, CREATED_DATE, UPDATED_DATE) VALUES
(2, 'take onions, add oil , add chicken , bake in oven ', 2, 'Chicken BBQ', false, {ts '2022-08-14 01:18:32'},{ts '2022-08-14 01:18:32'});

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(2, 'CHICKEN');

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(2, 'ONIONS');

INSERT INTO RECIPE (RECIPE_ID, INSTRUCTIONS, NUMBER_OF_SERVINGS, RECIPE_NAME, VEGETARIAN, CREATED_DATE, UPDATED_DATE) VALUES
(3, 'take onions , add Salmon , bake in oven', 2, 'Salmon Fry', false, {ts '2022-08-14 01:18:32'},{ts '2022-08-14 01:18:32'});

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(3, 'SALMON');

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(3, 'ONIONS');

INSERT INTO RECIPE (RECIPE_ID, INSTRUCTIONS, NUMBER_OF_SERVINGS, RECIPE_NAME, VEGETARIAN, CREATED_DATE, UPDATED_DATE) VALUES
(4, 'take bowl, add oil , add Spinach , fry them ', 1, 'Spinach Fry', true, {ts '2022-08-14 01:18:32'},{ts '2022-08-14 01:18:32'});

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(4, 'SPINACH');


INSERT INTO RECIPE (RECIPE_ID, INSTRUCTIONS, NUMBER_OF_SERVINGS, RECIPE_NAME, VEGETARIAN, CREATED_DATE, UPDATED_DATE) VALUES
(5, 'take bowl, add oil , add tomatoes, add onion , fry them ', 4, 'Tomato Curry', true, {ts '2022-08-14 01:18:32'},{ts '2022-08-14 01:18:32'});

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(5, 'POTATOES');

INSERT INTO RECIPE_ENTITY_INGREDIENTS VALUES
(5, 'TOMATOES');