CREATE SEQUENCE "MY_SEQ" START WITH 2 BELONGS_TO_TABLE;

CREATE TABLE RECIPE (
    "RECIPE_ID" BIGINT DEFAULT NEXT VALUE FOR "MY_SEQ" NOT NULL NULL_TO_DEFAULT SEQUENCE "MY_SEQ",
    "CREATED_DATE" TIMESTAMP,
    "INSTRUCTIONS" VARCHAR(255),
    "NUMBER_OF_SERVINGS" INTEGER,
    "RECIPE_NAME" VARCHAR(255),
    "UPDATED_DATE" TIMESTAMP,
    "IS_VEGETARIAN" BOOLEAN NOT NULL
);

ALTER TABLE RECIPE ADD CONSTRAINT "PK_1" PRIMARY KEY("RECIPE_ID");


CREATE TABLE RECIPE_ENTITY_INGREDIENTS (
    "RECIPE_ENTITY_RECIPE_ID" BIGINT NOT NULL,
    "INGREDIENTS" VARCHAR(255)
);


ALTER TABLE RECIPE_ENTITY_INGREDIENTS ADD CONSTRAINT "FK_1" FOREIGN KEY("RECIPE_ENTITY_RECIPE_ID") REFERENCES RECIPE("RECIPE_ID") NOCHECK;