CREATE SEQUENCE "MY_SEQ" START WITH 2 BELONGS_TO_TABLE;

CREATE TABLE RECIPE (
    "RECIPE_ID" BIGINT DEFAULT NEXT VALUE FOR "MY_SEQ" NOT NULL NULL_TO_DEFAULT SEQUENCE "MY_SEQ",
    "CREATED_DATE" TIMESTAMP,
    "INGREDIENTS" VARCHAR(255),
    "INSTRUCTIONS" VARCHAR(255),
    "NUMBER_OF_SERVINGS" INTEGER,
    "RECIPE_NAME" VARCHAR(255),
    "UPDATED_DATE" TIMESTAMP,
    "IS_VEGETARIAN" BOOLEAN NOT NULL
);